### PR TITLE
add php7.4

### PR DESCRIPTION
**Pull request by hjanuschka**
add php7.4 image.

i am unsure about the jsonnet change, guess someone with push rights need to push the image and then modify the tag to the sha256.

please let me know if you need me to change something.

### CODE REVIEW

**Comment by andresmgot** [comment]
Thanks for the update @hjanuschka! I have updated the PHP images and triggered the tests.

**Review by andresmgot — APPROVED** [review]

**Comment by andresmgot** [comment]
@hjanuschka it seems that the test for PHP 7.4 is failing. Can you check it?

**Comment by hjanuschka** [comment]
@andresmgot i am sorry, totally forgot to wait for CI.
i think i fixed it, by `rm /etc/nginx/sites-enabled/default` in the 7.4 image, i can run it locally, could you please update the image hashes and re-trigger the ci? (anyway i can run ci with custom built image?)

**Comment by andresmgot** [comment]
Thanks! Updated the images.

> anyway i can run ci with custom built image?

Well, you can use your personal DockerHub to temporarily push images there, I can later on push them to the `kubeless` repo when everything is ready.

**Comment by andresmgot** [comment]
Everything good now, thanks!

**Comment by hjanuschka** [comment]
hooray! thx!  keep up the great project!

**Pull request merged**
